language: go
before_install:
  - go get ./...
  - go get github.com/mitchellh/gox
script:
  - go fmt ./...
  - go vet ./...
  - gox -output "output/{{.Dir}}_{{.OS}}_{{.Arch}}"
deploy:
  provider: releases
  api_key:
    secure: aCYf9Guq+y63L/+QdQhUVc0iXZlc/E5zf9cfsrkuYHM6/HCCs2C4fETEaYMAJ6G2GPcAMpIeOpKBsHt1h1PK183iiZ++YqNbEMeMrz+4Y/y2Vndgswt4oWXmuHrUcD8I1UEn/50YtqOzkad5O8we8PvNdsTPVLw7rWHiuZCiIQ8lPoGnRaBsn2OINqJjnCZlgqyw7MHpCeTuG2hIFBhHeKO9UI9FkNRK4JtkUCofC+bh45u21TNxmMq9npYWxC0kXnPt0x/1j/pZFYEJ/yFMhnybxBI/qitqtGLezMcPiaS6p2EBkxoR8E3i7gzq/4iMJUl/fK8b1pxK3mfYd0CpUmZOwDEBPt8BCKh4HVZngVjS0qqisHwqpoCOHywNOk4Dwy3U+tr2NHJ9c1dktrZ6DrShuXfCSNajXN0BDbdo4UJNMPeEyM1E/CDT6pEEELhK85WiC7ijzTIhH7sKi6PAzPhKRoM8slvyEUDQPl5CgR+slE863HYBrLawXH7XeUCQzk+ZHCpeRhoEzX71B6vZiKHBIcrYYDUpUbDdCug+WxSs3sffVbLAUQ9fDEfI9Pgt1QIkHClSYdsU8XLiolfWyZLrJDCKJ4f3G+0zRRI3ymgpgGfyVIjHOUQG3XicAodJLL4OA6mwz1lp85r0seAR8SSGU3au/Lq7Upne3cGNQH0=
  file_glob: true
  file: "output/*"
  skip_cleanup: true
  on:
    branch: master
    tags: true
